### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by geodrinx** [Hacked-Crew/Magnetic-Declination#1]
Hello Aldo,

I had this :
Traceback (most recent call last):
  File "/Users/rrr/.qgis2/python/plugins/MagneticDeclination/Magnetic_declination.py", line 334, in simple_Calculate
    self.dlg.declination_lineEdit.setText(unicode(str(str(self.Rdeclination) + u'\u00B0')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 13: ordinal not in range(128)

**Comment by Hacked-Crew** [comment]
Roberto,

:D prova a sostituire il python allegato.
e dimmi se funziona. io non ho mai ricevuto questo errore, Win 7 e OSX 10.8.

Ciao
Aldo

2015-05-03 17:50 GMT+02:00 geodrinx <notifications@github.com>:

**Comment by geodrinx** [comment]
Aldo,


ho sostituito le due linee di codice,  ma mi ritorna questo:



 File
"/Users/rrr/.qgis2/python/plugins/MagneticDeclination/Magnetic_declination.py",
line 334, in simple_Calculate

self.dlg.declination_lineEdit.setText(unicode(str(str(self.Rdeclination) +
u'\N{DEGREE SIGN}')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in
position 13: ordinal not in range(128)

2015-05-03 18:22 GMT+02:00 Aldo Scorza <notifications@github.com>:

**Comment by geodrinx** [comment]
Non so se può essere utile, ma le coordinate che ho usato sono queste:

12.336593°     45.438243°

2015-05-03 19:22 GMT+02:00 Geo DrinX <geodrinx@gmail.com>:

**Comment by Hacked-Crew** [comment]
Ok Roberto,

that issue is generated because characters greater than 127 will cause an exception in unicode string.
i think the solution is replace again the lines 335 and 335 in

self.dlg.declination_lineEdit.setText(str(str(self.Rdeclination) + u'\N{DEGREE SIGN}'))
self.dlg.heading_lineEdit.setText(str(str(Rheading) + u'\N{DEGREE SIGN}'))

I'm sure this solves the issue

Bye
Aldo
